[workspace]
members = [
    "dump_tool",
    "img_tool",
    "minfs",
    "image",
    "gpt",
    "dump",
    "udisk",
    "melis-boot",
    "melis-data",
    "data_renderer",
    "xfel_spi_nor",
]
exclude = ["sd_fel_switcher"]
resolver = "2"

[workspace.dependencies]
binrw = "0.15"
thiserror = "2"
flate2 = "1"
