use std::collections::HashMap;
use std::{
    fs::{self, File},
    io::{self, Read, Seek, SeekFrom, Write},
    path::Path,
};

use binrw::{io::BufReader, BinRead, BinWrite};
use structs::*;

pub mod structs;

pub fn unpack_image(
    dump_path: impl AsRef<Path>,
    dest_path: impl AsRef<Path>,
) -> Result<(), String> {
    let dump_path = dump_path.as_ref();
    let dest_path = dest_path.as_ref();

    if dest_path.exists() {
        fs::remove_dir_all(dest_path)
            .map_err(|e| format!("Error deleting output directory: {}", e))?;
    }
    fs::create_dir_all(dest_path).map_err(|e| format!("Error creating output directory: {}", e))?;

    let file = File::open(dump_path).map_err(|e| format!("Error opening input file: {}", e))?;
    let mut reader = BufReader::new(file);

    let img_header =
        ImageHeader::read(&mut reader).map_err(|e| format!("Error reading input file: {}", e))?;

    let magic_str = bytes_to_string(&img_header.magic);
    if magic_str != IMAGE_MAGIC {
        return Err(format!(
            "Input file is not an Allwinner image (magic mismatch)"
        ));
    }

    if img_header.version != IMAGE_HEADER_VERSION && img_header.version != 0x0403 {
        return Err(format!(
            "Unsupported image version: 0x{:X}",
            img_header.version
        ));
    }

    reader
        .seek(SeekFrom::Start(img_header.item_offset as u64))
        .map_err(|e| format!("Error seeking to items offset: {}", e))?;

    let mut items = Vec::new();
    for i in 0..img_header.item_count {
        let item = ImageItem::read(&mut reader)
            .map_err(|e| format!("Error reading image item {}: {}", i, e))?;
        items.push(item);
    }

    let mut cfg_content = String::new();
    cfg_content.push_str(
        ";/**************************************************************************/\n",
    );
    cfg_content.push_str("; generated by melis_tools image crate\n");
    cfg_content.push_str(
        ";/**************************************************************************/\n\n",
    );
    cfg_content.push_str("[DIR_DEF]\n");
    cfg_content.push_str("INPUT_DIR = \"./\"\n\n");
    cfg_content.push_str("[FILELIST]\n");

    for item in &items {
        let filename = bytes_to_string(&item.name);
        let maintype = bytes_to_string(&item.main_type);
        let subtype = bytes_to_string(&item.sub_type);

        let out_file_path = dest_path.join(&filename);
        if let Some(parent) = out_file_path.parent() {
            fs::create_dir_all(parent).map_err(|e| format!("Failed to create directory: {}", e))?;
        }

        let mut file_reader =
            File::open(dump_path).map_err(|e| format!("Error reopening input file: {}", e))?;
        file_reader
            .seek(SeekFrom::Start(item.offset))
            .map_err(|e| format!("Error seeking to file data: {}", e))?;
        let mut buffer = vec![0u8; item.file_length as usize];
        file_reader
            .read_exact(&mut buffer)
            .map_err(|e| format!("Error reading file data for {}: {}", filename, e))?;

        let mut out_file = File::create(&out_file_path)
            .map_err(|e| format!("Error creating output file {}: {}", filename, e))?;
        out_file
            .write_all(&buffer)
            .map_err(|e| format!("Error writing file data for {}: {}", filename, e))?;

        cfg_content.push_str(&format!(
            "\t{{filename = \"{}\", maintype = \"{}\", subtype = \"{}\",}},\n",
            filename, maintype, subtype
        ));
    }

    cfg_content.push_str("\n[IMAGE_CFG]\n");
    cfg_content.push_str(&format!("version = 0x{:X}\n", img_header.image_version));
    cfg_content.push_str(&format!("pid = 0x{:X}\n", img_header.pid));
    cfg_content.push_str(&format!("vid = 0x{:X}\n", img_header.vid));
    cfg_content.push_str(&format!("hardwareid = 0x{:X}\n", img_header.hardware_id));
    cfg_content.push_str(&format!("firmwareid = 0x{:X}\n", img_header.firmware_id));
    cfg_content.push_str("filelist = FILELIST\n");

    let cfg_path = dest_path.join("image.cfg");
    fs::write(&cfg_path, cfg_content).map_err(|e| format!("Failed to write image.cfg: {}", e))?;

    Ok(())
}

pub fn pack_image(
    src_dir: impl AsRef<Path>,
    output_img_path: impl AsRef<Path>,
) -> Result<(), String> {
    let src_dir = src_dir.as_ref();
    let output_img_path = output_img_path.as_ref();

    let cfg_path = src_dir.join("image.cfg");
    if !cfg_path.exists() {
        return Err(format!("image.cfg not found in {:?}", src_dir));
    }

    let cfg_content =
        fs::read_to_string(&cfg_path).map_err(|e| format!("Failed to read image.cfg: {}", e))?;

    let mut main_types = HashMap::new();
    let mut vars = HashMap::new();
    let mut filelist_entries = Vec::new();
    let mut section = Section::None;

    let mut version = 0x100234;
    let mut pid = 0x1234;
    let mut vid = 0x8743;
    let mut hardwareid = 0x100;
    let mut firmwareid = 0x100;

    vars.insert("INPUT_DIR".to_string(), "./".to_string());

    for line in cfg_content.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with(';') {
            continue;
        }

        if line.starts_with('[') && line.ends_with(']') {
            section = match line {
                "[MAIN_TYPE]" => Section::MainType,
                "[FILELIST]" => Section::FileList,
                "[IMAGE_CFG]" => Section::ImageCfg,
                _ => Section::None,
            };
            continue;
        }

        match section {
            Section::MainType => {
                if let Some(eq_pos) = line.find('=') {
                    let key = line[..eq_pos].trim().to_string();
                    let val_part = line[eq_pos + 1..].trim();
                    if let Some(start) = val_part.find('"') {
                        if let Some(end) = val_part[start + 1..].find('"') {
                            let val = val_part[start + 1..start + 1 + end].to_string();
                            main_types.insert(key, val);
                        }
                    }
                }
            }
            Section::ImageCfg => {
                if let Some(eq_pos) = line.find('=') {
                    let key = line[..eq_pos].trim().to_string();
                    let val_part = line[eq_pos + 1..].trim();
                    let val_part = if let Some(idx) = val_part.find(';') {
                        &val_part[..idx]
                    } else if let Some(idx) = val_part.find("-->") {
                        &val_part[..idx]
                    } else if let Some(idx) = val_part.find("//") {
                        &val_part[..idx]
                    } else {
                        val_part
                    };
                    let val_str = val_part.trim().trim_end_matches(';');
                    let parse_num = |s: &str| -> Option<u32> {
                        let s = s.trim();
                        if s.starts_with("0x") || s.starts_with("0X") {
                            u32::from_str_radix(&s[2..], 16).ok()
                        } else {
                            s.parse::<u32>().ok()
                        }
                    };

                    match key.as_str() {
                        "version" => {
                            if let Some(n) = parse_num(val_str) {
                                version = n;
                            }
                        }
                        "pid" => {
                            if let Some(n) = parse_num(val_str) {
                                pid = n;
                            }
                        }
                        "vid" => {
                            if let Some(n) = parse_num(val_str) {
                                vid = n;
                            }
                        }
                        "hardwareid" => {
                            if let Some(n) = parse_num(val_str) {
                                hardwareid = n;
                            }
                        }
                        "firmwareid" => {
                            if let Some(n) = parse_num(val_str) {
                                firmwareid = n;
                            }
                        }
                        _ => {}
                    }
                }
            }
            Section::FileList => {
                if let Some((fn_expr, mt_expr, st_expr)) = parse_filelist_line(line) {
                    filelist_entries.push((fn_expr, mt_expr, st_expr));
                }
            }
            _ => {
                if let Some(eq_pos) = line.find('=') {
                    let key = line[..eq_pos].trim().to_string();
                    let val_part = line[eq_pos + 1..].trim();
                    if let Some(start) = val_part.find('"') {
                        if let Some(end) = val_part[start + 1..].find('"') {
                            let val = val_part[start + 1..start + 1 + end].to_string();
                            vars.insert(key, val);
                        }
                    }
                }
            }
        }
    }

    let num_files = filelist_entries.len();
    if num_files == 0 {
        return Err("No files specified in configuration FILELIST".to_string());
    }

    let mut items = Vec::new();
    let mut current_offset = (num_files as u64 + 1) * 1024;

    for (fn_expr, mt_expr, st_expr) in &filelist_entries {
        let resolved_fn = resolve_path_expr(fn_expr, &vars);
        let resolved_mt = resolve_value(mt_expr, &main_types);
        let resolved_st = resolve_value(st_expr, &main_types);

        let local_file_path = src_dir.join(&resolved_fn);
        if !local_file_path.exists() {
            return Err(format!("Source file {:?} not found", local_file_path));
        }

        let metadata = fs::metadata(&local_file_path)
            .map_err(|e| format!("Failed to read metadata for {:?}: {}", local_file_path, e))?;
        let original_length = metadata.len();
        let stored_length = align_up(original_length, 16);

        let item = ImageItem {
            version: IMAGE_ITEM_VERSION,
            size: 1024,
            main_type: pad_bytes(resolved_mt.as_bytes(), MAINTYPE_LEN as usize),
            sub_type: pad_bytes(resolved_st.as_bytes(), SUBTYPE_LEN as usize),
            attributes: 0,
            name: pad_bytes(resolved_fn.as_bytes(), FILE_PATH_LEN as usize),
            data_length: stored_length,
            file_length: original_length,
            offset: current_offset,
            encrypt_id: vec![0u8; 64],
            checksum: 0,
            reserved: vec![0u8; 640],
        };

        items.push(item);
        current_offset += align_up(original_length, 1024);
    }

    let img_header = ImageHeader {
        magic: pad_bytes(IMAGE_MAGIC.as_bytes(), 8),
        version: IMAGE_HEADER_VERSION,
        size: 0x60,
        attributes: 0x04D00000,
        image_version: version,
        image_size: current_offset,
        alignment: 1024,
        pid,
        vid,
        hardware_id: hardwareid,
        firmware_id: firmwareid,
        item_attr: 1,
        item_size: 1024,
        item_count: num_files as u32,
        item_offset: 1024,
        image_attr: 0,
        append_size: 0,
        append_offset: 0,
        reserved: vec![0u8; 12],
    };

    let mut out_file = File::create(output_img_path)
        .map_err(|e| format!("Failed to create output image: {}", e))?;

    let mut cursor = io::Cursor::new(Vec::new());
    img_header
        .write(&mut cursor)
        .map_err(|e| format!("Failed to serialize ImageHeader: {}", e))?;
    let mut header_bytes = cursor.into_inner();
    header_bytes.resize(1024, 0);
    out_file
        .write_all(&header_bytes)
        .map_err(|e| format!("Failed to write ImageHeader: {}", e))?;

    for item in &items {
        let mut cursor = io::Cursor::new(Vec::new());
        item.write(&mut cursor)
            .map_err(|e| format!("Failed to serialize ImageItem: {}", e))?;
        let mut item_bytes = cursor.into_inner();
        item_bytes.resize(1024, 0);
        out_file
            .write_all(&item_bytes)
            .map_err(|e| format!("Failed to write ImageItem: {}", e))?;
    }

    for (fn_expr, _, _) in &filelist_entries {
        let resolved_fn = resolve_path_expr(fn_expr, &vars);
        let local_file_path = src_dir.join(&resolved_fn);
        let mut file_content = fs::read(&local_file_path)
            .map_err(|e| format!("Failed to read source file {:?}: {}", local_file_path, e))?;

        let original_len = file_content.len() as u64;
        let padded_len = align_up(original_len, 1024);
        file_content.resize(padded_len as usize, 0);

        out_file
            .write_all(&file_content)
            .map_err(|e| format!("Failed to write payload for file {}: {}", resolved_fn, e))?;
    }

    Ok(())
}

fn bytes_to_string(bytes: &[u8]) -> String {
    let len = bytes.iter().position(|&c| c == 0).unwrap_or(bytes.len());
    String::from_utf8_lossy(&bytes[..len]).into_owned()
}

fn align_up(val: u64, alignment: u64) -> u64 {
    (val + alignment - 1) & !(alignment - 1)
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum Section {
    None,
    MainType,
    FileList,
    ImageCfg,
}

fn parse_filelist_line(line: &str) -> Option<(String, String, String)> {
    let start = line.find('{')?;
    let end = line.find('}')?;
    let content = &line[start + 1..end];

    let fn_idx = content.find("filename")?;
    let mt_idx = content.find("maintype")?;
    let st_idx = content.find("subtype")?;

    let fn_val = extract_value_between(content, fn_idx + "filename".len(), mt_idx)?;
    let mt_val = extract_value_between(content, mt_idx + "maintype".len(), st_idx)?;
    let st_val = extract_value_between(content, st_idx + "subtype".len(), content.len())?;

    Some((fn_val, mt_val, st_val))
}

fn extract_value_between(content: &str, start_pos: usize, end_pos: usize) -> Option<String> {
    let sub = &content[start_pos..end_pos];
    let eq_pos = sub.find('=')?;
    let val_part = &sub[eq_pos + 1..];
    let trimmed = val_part.trim().trim_end_matches(',');
    Some(trimmed.to_string())
}

fn resolve_path_expr(expr: &str, vars: &HashMap<String, String>) -> String {
    let mut result = String::new();
    for part in expr.split("..") {
        let part = part.trim();
        if part.starts_with('"') && part.ends_with('"') && part.len() >= 2 {
            result.push_str(&part[1..part.len() - 1]);
        } else if let Some(val) = vars.get(part) {
            result.push_str(val);
        } else {
            if let Some(start) = part.find('"') {
                if let Some(end) = part[start + 1..].find('"') {
                    result.push_str(&part[start + 1..start + 1 + end]);
                    continue;
                }
            }
        }
    }
    result
}

fn resolve_value(expr: &str, map: &HashMap<String, String>) -> String {
    let expr = expr.trim();
    if expr.starts_with('"') && expr.ends_with('"') && expr.len() >= 2 {
        expr[1..expr.len() - 1].to_string()
    } else if let Some(val) = map.get(expr) {
        val.clone()
    } else {
        expr.to_string()
    }
}
